version: '3.2'

services:
  html5-validator:
    image: magnetikonline/html5validator
    network_mode: bridge

  musicbrainz-test-database:
    build:
      cache_from:
        - metabrainz/musicbrainz-test-database:${CACHE_FROM:-latest}
      context: ../
      dockerfile: docker/Dockerfile.test-database
    image: metabrainz/musicbrainz-test-database:${IMAGE_TAG:-latest}
    network_mode: bridge

  musicbrainz-tests:
    build:
      cache_from:
        - metabrainz/musicbrainz-tests:${CACHE_FROM:-master}
      context: ../
      dockerfile: docker/Dockerfile.tests
    container_name: musicbrainz-tests
    image: metabrainz/musicbrainz-tests:${IMAGE_TAG:-latest}
    links:
      - html5-validator
      - musicbrainz-redis-cache
      - musicbrainz-redis-store
      - musicbrainz-test-database
    network_mode: bridge

  musicbrainz-redis-cache:
    image: redis:3.2-alpine
    network_mode: bridge
    command: redis-server --maxmemory 8MB --maxmemory-policy allkeys-lru --save ""

  musicbrainz-redis-store:
    image: redis:3.2-alpine
    network_mode: bridge
    command: redis-server --appendonly yes
